name: Benchmark.js Example
on:
  push:
    branches:
      - dev

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JavaScript benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.22.2
          run_install: true
      - name: Run benchmark
        run: npm i -g pnpm && pnpm i && pnpm bench:new
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark.js Benchmark
          tool: "customBiggerIsBetter"
          output-file-path: benchmark-runner/dist/bechmark-action-otuput.txt
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-pages-branch: dev
          auto-push: false
          # Show alert with commit comment on detecting possible performance regression
          # alert-threshold: "200%"
          # comment-on-alert: true
          # fail-on-alert: 
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
